import type { Paper } from "@/components/svelte/bib/BibState.svelte";

export const papers = {
  "mst/FolDamFeiHug.etal93": {
    year: "1993",
    publisher: "Addison-Wesley",
    title: "Introduction to Computer Graphics",
    author:
      "Foley, James D. and van Dam, Andries and\nFeiner, Stephen K. and Hughes, John F. and Phillips, R.",
    ENTRYTYPE: "book",
    ID: "FolDamFeiHug.etal93",
    authors: [
      "Foley, James D.",
      "van Dam, Andries and\nFeiner, Stephen K.",
      "Hughes, John F.",
      "Phillips, R.",
    ],
  },
  "mst/Kobbelt97-USHDR": {
    doi: "10.1111/1467-8659.16.3conferenceissue.36",
    year: "1997",
    pages: "C347-C355",
    number: "3",
    volume: "16",
    journal: "Computer Graphics Forum",
    title:
      "Using Subdivision on Hierarchical Data to Reconstruct Radiosity\nDistribution",
    author: "L. Kobbelt and M. Stamminger and H.-P. Seidel",
    ENTRYTYPE: "article",
    ID: "Kobbelt97-USHDR",
    authors: ["L. Kobbelt", "M. Stamminger", "H.-P. Seidel"],
  },
  "mst/Lafortune97-NARF": {
    doi: "10.1145/258734.258801",
    year: "1997",
    pages: "117-126",
    volume: "31",
    publisher: "Proc. SIGGRAPH '97",
    title: "Non-Linear Approximation of Reflectance Functions",
    author:
      "Eric P. Lafortune and Sing-Choong Foo and Kenneth E. Torrance and\nDonald P. Greenberg",
    ENTRYTYPE: "book",
    ID: "Lafortune97-NARF",
    authors: [
      "Eric P. Lafortune",
      "Sing-Choong Foo",
      "Kenneth E. Torrance and\nDonald P. Greenberg",
    ],
  },
  "mst/Lous90": {
    doi: "10.1111/j.1467-8659.1990.tb00430.x",
    pages: "371-372",
    year: "1990",
    month: "December",
    number: "4",
    volume: "9",
    journal: "Computer Graphics Forum",
    title:
      "Report on the {F}irst {E}urographics {W}orkshop on {V}isualization in\n{S}cientific {C}omputing",
    author: "Y. Le Lous",
    ENTRYTYPE: "article",
    ID: "Lous90",
    authors: ["Y. Le Lous"],
  },
  "mst/Seidel93": {
    doi: "10.1145/169728.169726",
    pages: "1-34",
    year: "1993",
    month: "January",
    number: "1",
    volume: "12",
    journal: "ACM TOG",
    title:
      "Polar Forms for Geometrically Continuous Spline Curves of\nArbitrary Degree",
    author: "Seidel, Hans-Peter",
    ENTRYTYPE: "article",
    ID: "Seidel93",
    authors: ["Seidel, Hans-Peter"],
  },
  "mst/Mutex_Paradigm": {
    doi: "10.1007/978-3-642-21834-7_13",
    pages: "228-247",
    year: "2011",
    journal: "Applications and Theory of Petri Nets",
    title: "The Mutex Paradigm Of Concurrency",
    author: "Kleijn, J., Koutny, M.",
    ENTRYTYPE: "article",
    ID: "Mutex_Paradigm",
    authors: ["Kleijn, J., Koutny, M."],
  },
  "mst/ZHAO2015156": {
    title: "Demand for multi-scale weather data for regional crop modeling",
    journal: "Agricultural and Forest Meteorology",
    volume: "200",
    pages: "156-171",
    year: "2015",
    issn: "0168-1923",
    doi: "https://doi.org/10.1016/j.agrformet.2014.09.026",
    url: "https://www.sciencedirect.com/science/article/pii/S0168192314002500",
    author:
      "Gang Zhao and Stefan Siebert and Andreas Enders and Ehsan Eyshi Rezaei and Changqing Yan and Frank Ewert",
    ENTRYTYPE: "article",
    ID: "ZHAO2015156",
    authors: [
      "Gang Zhao",
      "Stefan Siebert",
      "Andreas Enders",
      "Ehsan Eyshi Rezaei",
      "Changqing Yan",
      "Frank Ewert",
    ],
  },
  "mst/trautner2021line": {
    title:
      "Line Weaver: Importance-Driven Order Enhanced Rendering of Dense Line Charts",
    author: "Trautner, Thomas and Bruckner, Stefan",
    journal: "Computer Graphics Forum",
    volume: "40",
    number: "3",
    pages: "399-410",
    year: "2021",
    ENTRYTYPE: "journal",
    ID: "trautner2021line",
    authors: ["Trautner, Thomas", "Bruckner, Stefan"],
  },
  "mst/StructuredBrushing": {
    doi: "https://doi.org/10.1111/cgf.12901",
    author:
      "Radoš, S. and Splechtna, R. and Matković, K. and Đuras, M. and Gröller, E. and Hauser, H.",
    title:
      "Towards Quantitative Visual Analytics with Structured Brushing and Linked Statistics",
    journal: "Computer Graphics Forum",
    year: "2015",
    month: "01",
    volume: "35",
    number: "3",
    pages: "251-260",
    ENTRYTYPE: "article",
    ID: "StructuredBrushing",
    authors: [
      "Radoš, S.",
      "Splechtna, R.",
      "Matković, K.",
      "Đuras, M.",
      "Gröller, E.",
      "Hauser, H.",
    ],
  },
  "mst/Albero": {
    author:
      "Diehl, A. and Pelorosso, L. and Delrieux, C. and Matković, K. and Ruiz, J. and Gröller, M.E. and Bruckner, S.",
    title:
      "Albero: A Visual Analytics Approach for Probabilistic Weather Forecasting",
    journal: "Computer Graphics Forum",
    volume: "36",
    number: "7",
    year: "2017",
    month: "10",
    pages: "135-144",
    doi: "https://doi.org/10.1111/cgf.13279",
    url: "https://onlinelibrary.wiley.com/doi/abs/10.1111/cgf.13279",
    ENTRYTYPE: "article",
    ID: "Albero",
    authors: [
      "Diehl, A.",
      "Pelorosso, L.",
      "Delrieux, C.",
      "Matković, K.",
      "Ruiz, J.",
      "Gröller, M.E.",
      "Bruckner, S.",
    ],
  },
  "mst/YANG19931": {
    abstract:
      "This paper is a survey of fuzzy set theory applied in cluster analysis. These fuzzy clustering algorithms have been widely studied and applied in a variety of substantive areas. They also become the major techniques in cluster analysis. In this paper, we give a survey of fuzzy clustering in three categories. The first category is the fuzzy clustering based on fuzzy relation. The second one is the fuzzy clustering based on objective function. Finally, we give an overview of a nonparametric classifier. That is the fuzzy generalized k-nearest neighbor rule.",
    author: "M.-S. Yang",
    url: "https://www.sciencedirect.com/science/article/pii/089571779390202A",
    doi: "https://doi.org/10.1016/0895-7177(93)90202-A",
    issn: "0895-7177",
    year: "1993",
    pages: "1-16",
    number: "11",
    volume: "18",
    journal: "Mathematical and Computer Modelling",
    title: "A survey of fuzzy clustering",
    ENTRYTYPE: "article",
    ID: "YANG19931",
    authors: ["M.-S. Yang"],
  },
  "mst/fan2021sketch": {
    title:
      "On sketch-based selections from scatterplots using KDE, compared to Mahalanobis and CNN brushing",
    author: "Fan, Chaoran and Hauser, Helwig",
    journal: "IEEE Computer Graphics and Applications",
    volume: "41",
    number: "5",
    pages: "67-78",
    year: "2021",
    ENTRYTYPE: "article",
    ID: "fan2021sketch",
    authors: ["Fan, Chaoran", "Hauser, Helwig"],
  },
  "mst/9120181": {
    author: "Zhou, Shuisheng and Li, Dong and Zhang, Zhuan and Ping, Rui",
    journal: "IEEE Transactions on Fuzzy Systems",
    title: "A New Membership Scaling Fuzzy C-Means Clustering Algorithm",
    year: "2021",
    volume: "29",
    number: "9",
    pages: "2810-2818",
    doi: "10.1109/TFUZZ.2020.3003441",
    ENTRYTYPE: "article",
    ID: "9120181",
    authors: ["Zhou, Shuisheng", "Li, Dong", "Zhang, Zhuan", "Ping, Rui"],
  },
  "mst/ben2015computational": {
    title:
      "Computational feasibility of clustering under clusterability assumptions",
    author: "Ben-David, Shai",
    journal: "arXiv preprint arXiv:1501.00437",
    year: "2015",
    ENTRYTYPE: "article",
    ID: "ben2015computational",
    authors: ["Ben-David, Shai"],
    doi: "https://doi.org/10.48550/arXiv.1501.00437",
  },
  "mst/wei2011parallel": {
    title: "Parallel clustering for visualizing large scientific line data",
    author:
      "Wei, Jishang and Yu, Hongfeng and Chen, Jacqueline H and Ma, Kwan-Liu",
    journal: "2011 IEEE Symposium on Large Data Analysis and Visualization",
    pages: "47-55",
    year: "2011",
    ENTRYTYPE: "inproceedings",
    ID: "wei2011parallel",
    authors: [
      "Wei, Jishang",
      "Yu, Hongfeng",
      "Chen, Jacqueline H",
      "Ma, Kwan-Liu",
    ],
  },

  "mst/2022_gch_andra": {
    author:
      "Andra Popa and Francesca Gabrieli and Thomas Kroes and Anna Krekeler and Matthias Alfeld and Boudewijn Lelieveldt and Elmar Eisemann and Thomas Höllt",
    title: "Visual Analysis of RIS Data for Endmember Selection",
    journal:
      "Proceedings of Eurographics Workshop on Graphics and Cultural Heritage Short Papers",
    year: "2022",
    doi: "10.2312/gch.20221233",
    ENTRYTYPE: "inproceedings",
    ID: "2022_gch_andra",
    authors: [
      "Andra Popa",
      "Francesca Gabrieli",
      "Thomas Kroes",
      "Anna Krekeler",
      "Matthias Alfeld",
      "Boudewijn Lelieveldt",
      "Elmar Eisemann",
      "Thomas Höllt",
    ],
  },
  "mst/shimony2002automated": {
    title:
      "Automated fuzzy clustering of neuronal pathways in diffusion tensor tracking",
    author:
      "Shimony, Joshua S and Snyder, Avi Z and Lori, Nicholas and Conturo, TE",
    journal: "Proc. Intl. Soc. Mag. Reson. Med",
    volume: "10",
    pages: "1--1",
    year: "2002",
    ENTRYTYPE: "journal",
    ID: "shimony2002automated",
    authors: [
      "Shimony, Joshua S",
      "Snyder, Avi Z",
      "Lori, Nicholas",
      "Conturo, TE",
    ],
  },
  "mst/10410948": {
    author:
      "Wang, Zhenglin and Walsh, Kerry and Sabrina, Fariza and Piyathilaka, Lasitha and Lin, Yufeng",
    journal:
      "2023 International Conference on Digital Image Computing: Techniques and Applications (DICTA)",
    title:
      "Clustering-TinyPointNet for Fast Large-scale Point Cloud Semantic Segmentation",
    year: "2023",
    pages: "229-236",
    doi: "10.1109/DICTA60407.2023.00039",
    ENTRYTYPE: "inproceedings",
    ID: "10410948",
    authors: [
      "Wang, Zhenglin",
      "Walsh, Kerry",
      "Sabrina, Fariza",
      "Piyathilaka, Lasitha",
      "Lin, Yufeng",
    ],
  },

  "mst/rsos.211189": {
    author:
      "Butyaev, A. and Drogaris, C. and Tremblay-Savard, O. and Waldispühl, J.",
    title:
      "Human-supervised clustering of multidimensional data using crowdsourcing",
    journal: "Royal Society Open Science",
    year: "2022",
    volume: "9",
    issue: "5",
    doi: "10.1098/rsos.211189",
    ENTRYTYPE: "article",
    ID: "rsos.211189",
    authors: [
      "Butyaev, A.",
      "Drogaris, C.",
      "Tremblay-Savard, O.",
      "Waldispühl, J.",
    ],
  },
  "mst/Amagata2023EfficientDC": {
    title:
      "Efficient Density-peaks Clustering Algorithms on Static and Dynamic Data in Euclidean Space",
    author: "Daichi Amagata and Takahiro Hara",
    journal: "ACM Transactions on Knowledge Discovery from Data",
    year: "2023",
    volume: "18",
    pages: "1 - 27",
    url: "https://api.semanticscholar.org/CorpusID:259346562",
    ENTRYTYPE: "article",
    ID: "Amagata2023EfficientDC",
    authors: ["Daichi Amagata", "Takahiro Hara"],
  },
  "mst/Chen2022ParallelGC": {
    title:
      "Parallel gravitational clustering based on grid partitioning for large-scale data",
    author:
      "Lei Chen and Fadong Chen and Zhaohua Liu and Mingyang Lv and Tingqin He and Shiwen Zhang",
    journal: "Applied Intelligence",
    year: "2022",
    volume: "53",
    pages: "2506-2526",
    url: "https://api.semanticscholar.org/CorpusID:248707931",
    ENTRYTYPE: "article",
    ID: "Chen2022ParallelGC",
    authors: [
      "Lei Chen",
      "Fadong Chen",
      "Zhaohua Liu",
      "Mingyang Lv",
      "Tingqin He",
      "Shiwen Zhang",
    ],
  },
} as const satisfies { [key: `mst/${string}`]: Paper };

export type MasterPapers = typeof papers;
